### ISSUE TITLE
改行なき意思の表示を修正すべきか、否か

### ISSUE THREAD

**Issue by tobynet** [arigato-java/JavaBrowser.crx#2]
＠同志諸兄 ごく一部の格言において、意図しない表示が確認されています。

我々としては、何らかの対抗策を打ち出す立場にあるのではないでしょうか。
今一度、人民に我々の力を示すべきです。

該当のイシューは 「Issues」タブでは起きていません！ SNS で起きています！

![image](https://user-images.githubusercontent.com/20859/27188830-67511c48-522a-11e7-8538-02a0736b15f3.png)

参考: https://twitter.com/arclisp/status/875312353222447106

対処案
* [ ] 特定の "u" に対してフィルタなりをかける
  * [ ] "t" に対して `┓` `┃` `┛` を語尾に\nつける置換を行う。

**Comment by origamium** [comment]
身も蓋もない事を言うと、見た目が雑な方もそこそこ面白いというのがあります（しかし、実際に体裁が崩れず見えたらそれはそれで面白そう、というのも）

**Comment by tomari** [comment]
アップストリーム（ジャバ評議会）より、修正してステージングで動作確認中との連絡がありました。間もなく本番環境にも修正が反映されるのではないかと思います。

**Comment by tomari** [comment]
いま確認したら治ってるっぽいのでクローズにさせてもらいます。

**Comment by tobynet** [comment]
kakugen.json の方の修正、ありがとうございます
