### ISSUE TITLE
検討: Google Analytics を外せるか？

### ISSUE THREAD

**Issue by tomari** [arigato-java/JavaBrowser.crx#7]
近年のプライバシーに関する議論の進展に対応したい。
ユーザへのメリットが見えにくいため、外すことはできないか。

コミット https://github.com/arigato-java/JavaBrowser.crx/commit/7927abdca394256dc70c5098cafcdbc0ab301718

**Comment by tobynet** [comment]
活用しておりませんでした ＆ ユーザーのプライバシー保護のため外すこととします。

**Comment by tobynet** [comment]
とりいそぎ   https://github.com/arigato-java/JavaBrowser.crx/commit/01e5e2fbf35682fc216864b7246bbcd2590cea73
リリース後、close いたします
